const PDFDocument = require('pdfkit');

exports.generateInvoicePDF = (invoice) => new Promise((resolve, reject) => {
  const doc = new PDFDocument({ size: 'A4', margin: 50 });
  const buffers = [];
  doc.on('data', b => buffers.push(b));
  doc.on('end', () => resolve(Buffer.concat(buffers)));
  doc.on('error', reject);

  const { company, customer, lineItems } = invoice;
  const RED = '#DC2626';

  // Header
  doc.rect(0, 0, 595, 80).fill(RED);
  doc.fillColor('white').fontSize(24).font('Helvetica-Bold').text('INVOICE', 50, 28);
  doc.fontSize(12).font('Helvetica').text(invoice.invoiceNumber, 50, 55);

  // Company info
  doc.fillColor('#111').fontSize(10).font('Helvetica-Bold')
    .text(company.name, 350, 90, { align: 'right' });
  doc.font('Helvetica').fillColor('#555')
    .text(company.email, 350, 104, { align: 'right' })
    .text(company.phone || '', 350, 118, { align: 'right' });

  // Bill To
  doc.fillColor(RED).fontSize(9).font('Helvetica-Bold').text('BILL TO', 50, 110);
  doc.fillColor('#111').fontSize(11).font('Helvetica-Bold').text(customer.name, 50, 122);
  doc.font('Helvetica').fillColor('#555').fontSize(10)
    .text(customer.email || '', 50, 136)
    .text(customer.phone || '', 50, 150);

  // Invoice details
  doc.fillColor(RED).fontSize(9).font('Helvetica-Bold').text('INVOICE DETAILS', 350, 150);
  const details = [
    ['Invoice #', invoice.invoiceNumber],
    ['Issue Date', new Date(invoice.issueDate).toLocaleDateString()],
    ['Due Date', new Date(invoice.dueDate).toLocaleDateString()],
    ['Status', invoice.status.toUpperCase()],
  ];
  details.forEach(([label, value], i) => {
    doc.fillColor('#555').font('Helvetica').fontSize(9).text(label + ':', 350, 164 + i*14)
    doc.fillColor('#111').font('Helvetica-Bold').text(value, 430, 164 + i*14);
  });

  // Line Items Table
  let y = 230;
  doc.rect(50, y, 495, 22).fill(RED);
  const cols = { desc: 55, qty: 320, rate: 380, amount: 470 };
  doc.fillColor('white').fontSize(9).font('Helvetica-Bold')
    .text('DESCRIPTION', cols.desc, y+7)
    .text('QTY', cols.qty, y+7)
    .text('RATE', cols.rate, y+7)
    .text('AMOUNT', cols.amount, y+7);

  y += 28;
  lineItems.forEach((item, i) => {
    if (i % 2 === 0) doc.rect(50, y-4, 495, 20).fill('#FEF2F2');
    doc.fillColor('#111').font('Helvetica').fontSize(9)
      .text(item.description, cols.desc, y, { width: 250, lineBreak: false })
      .text(item.quantity, cols.qty, y)
      .text(`$${item.rate.toFixed(2)}`, cols.rate, y)
      .text(`$${item.amount.toFixed(2)}`, cols.amount, y);
    y += 20;
  });

  // Totals
  y += 10;
  doc.moveTo(350, y).lineTo(545, y).strokeColor('#E5E7EB').stroke();
  y += 8;
  const totals = [
    ['Subtotal', `$${invoice.subtotal.toFixed(2)}`],
    invoice.discountAmount ? ['Discount', `-$${invoice.discountAmount.toFixed(2)}`] : null,
    invoice.taxAmount ? [`Tax (${invoice.taxRate}%)`, `$${invoice.taxAmount.toFixed(2)}`] : null,
    invoice.shippingCharge ? ['Shipping', `$${invoice.shippingCharge.toFixed(2)}`] : null,
  ].filter(Boolean);

  totals.forEach(([l, v]) => {
    doc.fillColor('#555').font('Helvetica').fontSize(10).text(l, 350, y)
      .fillColor('#111').font('Helvetica-Bold').text(v, 460, y);
    y += 16;
  });

  doc.moveTo(350, y).lineTo(545, y).strokeColor(RED).lineWidth(1.5).stroke();
  y += 6;
  doc.rect(350, y, 195, 28).fill(RED);
  doc.fillColor('white').font('Helvetica-Bold').fontSize(12)
    .text('TOTAL DUE', 358, y+8)
    .text(`$${invoice.total.toFixed(2)}`, 450, y+8);

  // Notes
  if (invoice.notes) {
    doc.fillColor(RED).font('Helvetica-Bold').fontSize(9).text('NOTES', 50, y + 40);
    doc.fillColor('#555').font('Helvetica').fontSize(9).text(invoice.notes, 50, y + 52, { width: 300 });
  }

  // Footer
  doc.rect(0, 790, 595, 50).fill('#111');
  doc.fillColor('#aaa').fontSize(8).font('Helvetica')
    .text('Generated by InvoiceFlow — invoiceflow.com', 50, 808, { align: 'center', width: 495 });

  doc.end();
});